name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - develop*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: echo
      run: echo "This is a placeholder for the Hugging Face sync action. Uncomment the sync step when ready."

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true

    - name: Push to hub
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: git push https://harish-anandaramanujam:$HF_TOKEN@huggingface.co/spaces/harish-anandaramanujam/career-conversations-gpt-v2 develop-v2